/* Weapons have independent era tags. conflictSlots reserves a wardrobe slot for
   ordinary wearable/carried objects; use [] for weapons with no wardrobe overlap. */
(function(root) {
  const physical = [], metaphorical = [];
  const add = (list, eras, name, advantage = '', conflictSlots = []) => list.push({id:`weapon-${physical.length + metaphorical.length}`, name, eras:eras.split(' '), advantage, conflictSlots, kind:list === physical ? 'physical' : 'metaphorical'});
  add(physical,'contemporary historical fantasy sci-fi','Reinforced fighting gloves','', ['gloves']);
  add(physical,'contemporary historical fantasy','Knuckle guards','', ['hands']);
  add(physical,'contemporary historical fantasy sci-fi','Padded sparring hand wraps','', ['gloves']);
  add(physical,'historical fantasy','Arming sword');
  add(physical,'historical fantasy','Basket-hilt rapier');
  add(physical,'historical fantasy','Heavy mace');
  add(physical,'historical fantasy','Notched battle axe');
  add(physical,'historical fantasy','Ash-shaft spear');
  add(physical,'contemporary historical fantasy','Plain utility knife');
  add(physical,'historical fantasy','Recurved bow');
  add(physical,'historical fantasy','Wood-stock crossbow');
  add(physical,'historical fantasy','Braided sling');
  add(physical,'historical','Flintlock pistol');
  add(physical,'contemporary','Compact concealed pistol');
  add(physical,'contemporary','Weathered hunting rifle');
  add(physical,'contemporary sci-fi','Compact stun baton');
  add(physical,'contemporary historical fantasy sci-fi','Heavy walking cane','', ['carried']);
  add(physical,'contemporary historical','Sturdy umbrella','', ['carried']);
  add(physical,'contemporary historical fantasy sci-fi','Broken chair leg');
  add(physical,'contemporary historical fantasy sci-fi','Length of heavy chain');
  add(physical,'contemporary historical','Dented frying pan');
  add(physical,'fantasy','Rune-etched staff');
  add(physical,'fantasy','Crystal-tipped wand');
  add(physical,'fantasy','Spectral blade');
  add(physical,'fantasy','Storm-bound orb');
  add(physical,'sci-fi','Plasma sidearm');
  add(physical,'sci-fi','Collapsible energy spear');
  add(physical,'sci-fi','Gravity gauntlet','', ['gloves']);
  add(physical,'sci-fi','Floating guardian drone');
  add(metaphorical,'contemporary sci-fi','Incriminating recording','can expose a compromising conversation');
  add(metaphorical,'contemporary historical fantasy sci-fi','Forged invitation','can gain access to a restricted gathering');
  add(metaphorical,'contemporary historical fantasy sci-fi','Damaging secret','can undermine someone’s standing');
  add(metaphorical,'contemporary historical fantasy sci-fi','Political influence','can sway people who make decisions');
  add(metaphorical,'contemporary historical fantasy sci-fi','Legal authority','can compel cooperation within their jurisdiction');
  add(metaphorical,'contemporary historical fantasy sci-fi','Intimidating reputation','makes people hesitate before challenging them');
  add(metaphorical,'contemporary historical fantasy sci-fi','Control of the guest list','can decide who gets into the room');
  add(metaphorical,'contemporary historical fantasy sci-fi','Signed debt ledger','can call in obligations at a difficult moment');
  add(metaphorical,'contemporary historical fantasy sci-fi','Sealed letter of introduction','can open doors through a trusted name');
  add(metaphorical,'contemporary historical fantasy sci-fi','Official signet ring','can lend apparent authority to a demand', ['hands']);
  add(metaphorical,'contemporary historical fantasy sci-fi','Document-filled briefcase','holds evidence that can change a negotiation', ['carried']);
  add(metaphorical,'contemporary historical fantasy sci-fi','Network of favors','can find help through reciprocal obligations');
  add(metaphorical,'contemporary historical fantasy sci-fi','Exceptional memory','can recall details others hoped were forgotten');
  add(metaphorical,'contemporary historical fantasy sci-fi','Public credibility','can make an accusation difficult to dismiss');
  add(metaphorical,'contemporary historical fantasy sci-fi','Control of a scarce resource','can bargain with something others need');
  add(metaphorical,'historical fantasy','Royal writ','can invoke the ruler’s delegated authority');
  add(metaphorical,'fantasy','Binding oath token','can remind a sworn party of a magical obligation');
  add(metaphorical,'sci-fi','Privileged access credential','can enter systems closed to ordinary users');
  const api = {physical, metaphorical}; root.WeaponData=api;
  if(typeof module !== 'undefined') module.exports=api;
})(globalThis);
